"""Policy-file scaffolding for new agent-contracts installs."""

from __future__ import annotations

from pathlib import Path


DEFAULT_POLICY_FILENAME = "agent-contracts.yml"


def render_policy(workspace_root: str = ".") -> str:
    """Return a starter policy file for a local agent runtime.

    The package intentionally has no YAML runtime dependency. This file is a
    human-editable scaffold that teams can wire into their own config loader.
    """

    return f"""# agent-contracts starter policy
# Generated by: agent-contracts init
#
# Keep this file close to the agent runtime it governs. Start strict, then widen
# only for tools and paths that have a concrete product need.

workspace:
  root: {workspace_root}
  path_keys:
    - path
    - file
    - filename

tools:
  allowlist:
    - read_file
    - write_file
    - list_files
    - web_search
    - run_tests

shell:
  tool_names:
    - shell
    - bash
    - run_shell
    - exec_command

loop_guard:
  max_edits_per_path: 3

completion_evidence:
  required_for_claims:
    - done
    - fixed
    - shipped
    - deployed
  accepted_evidence:
    - command output
    - file path
    - URL
    - commit hash

secrets:
  block_in_tool_params: true
  block_in_responses: true
"""


def write_policy(path: str | Path, workspace_root: str = ".", force: bool = False) -> Path:
    """Write a starter policy file and return its path."""

    target = Path(path)
    if target.exists() and not force:
        raise FileExistsError(f"{target} already exists; pass force=True to overwrite")
    target.write_text(render_policy(workspace_root), encoding="utf-8")
    return target
