#!/usr/bin/env python3
"""Find declared human checkpoints and turn them into a public work contract."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

PATTERNS = (
    re.compile(r"human[- ]in[- ]the[- ]loop", re.I),
    re.compile(r"human (?:must )?(?:approve|review|verify|check)", re.I),
    re.compile(r"manual(?:ly)? (?:approval|review|verification|check)", re.I),
    re.compile(r"requires? (?:a )?(?:human|operator) (?:approval|review|verification)", re.I),
)
SKIP_PARTS = {".git", "node_modules", ".venv", "venv", "dist", "build"}
TEXT_SUFFIXES = {".md", ".txt", ".py", ".js", ".ts", ".tsx", ".go", ".rs", ".java", ".yml", ".yaml", ".toml"}


def scan(root: Path) -> list[dict]:
    findings: list[dict] = []
    for path in sorted(root.rglob("*")):
        if not path.is_file() or path.suffix.lower() not in TEXT_SUFFIXES:
            continue
        if any(part in SKIP_PARTS for part in path.relative_to(root).parts):
            continue
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except (UnicodeDecodeError, OSError):
            continue
        for number, line in enumerate(lines, 1):
            if any(pattern.search(line) for pattern in PATTERNS):
                excerpt = re.sub(r"\s+", " ", line).strip()[:240]
                findings.append({"path": str(path.relative_to(root)), "line": number, "excerpt": excerpt})
    return findings


def prospectus(findings: list[dict]) -> dict:
    canonical = json.dumps(findings, sort_keys=True, separators=(",", ":"))
    fingerprint = hashlib.sha256(canonical.encode()).hexdigest()[:12]
    rows = "\n".join(f"- `{item['path']}:{item['line']}` — {item['excerpt']}" for item in findings[:25])
    body = f"""<!-- review-debt-ipo:{fingerprint} -->
## Review Debt IPO

This repository declares recurring human checkpoints. The debt is now open for deletion proof—not removal by assertion.

### Checkpoints discovered
{rows}

### Claim contract
Reply with the checkpoint you are claiming. A valid deletion proof must include:

1. a failing test or replay showing why the review exists;
2. a deterministic control that contains that failure; and
3. a passing test proving the named review can be removed or narrowed.

The maintainer decides whether the proof earns deletion. Generated by [Review Debt IPO](https://github.com/impartshadow/agent-contracts/tree/main/review-debt-ipo).
"""
    return {"fingerprint": fingerprint, "count": len(findings), "findings": findings, "title": f"Review Debt IPO: {len(findings)} human checkpoints open for deletion proof", "body": body}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--output", type=Path, default=Path("review-debt-ipo.json"))
    args = parser.parse_args()
    result = prospectus(scan(args.root.resolve()))
    args.output.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"count": result["count"], "fingerprint": result["fingerprint"], "output": str(args.output)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
